name: .NET

on:
  push:
    branches: [ "development", "stable" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Preparing
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restoring
      run: dotnet restore
    - name: Building
      run: |
          if [[ "${{ github.ref_name }}" == "stable" ]]; then
            dotnet build --no-restore /p:BuildNumber=${{ github.event.run_number }}
          else
            dotnet build --no-restore /p:BuildNumber=${{ github.event.run_number }} /p:VersionSuffix=dev
          fi
    - name: Testing
      run: dotnet test --no-build --verbosity normal
    - name: Publishing
      if: ${{ github.ref_name == 'development' || github.ref_name == 'stable' }}
      run: |
        dotnet nuget push --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json ./Packages/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}
